// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropDownController from "./drop_down_controller.js"
application.register("drop-down", DropDownController)

import PromoCodeController from "./promo_code_controller.js"
application.register("promo-code", PromoCodeController)

import TabController from "./tab_controller.js"
application.register("tab", TabController)
